# Cargo manifest
# https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "xtask"
description = "Cargo xtask."
version = "0.1.0"
edition.workspace = true

[[bin]]
name = "xtask"
path = "src/main.rs"

[dependencies]
clap.workspace = true
iron-bin.workspace = true
